import './styles/main.styl';
import './components/slider/plugin';
import './components/slider/app';
import './components/slider/view';
import './components/slider/model';
import './components/slider/controller';
import './components/slider/runner/RunnerView';
import './components/demo/DemoView';
import './pages/index/index';
